/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DetectionService } from "../detection.service";
import { DetectionCreateInput } from "./DetectionCreateInput";
import { Detection } from "./Detection";
import { DetectionFindManyArgs } from "./DetectionFindManyArgs";
import { DetectionWhereUniqueInput } from "./DetectionWhereUniqueInput";
import { DetectionUpdateInput } from "./DetectionUpdateInput";
import { KeywordFindManyArgs } from "../../keyword/base/KeywordFindManyArgs";
import { Keyword } from "../../keyword/base/Keyword";
import { KeywordWhereUniqueInput } from "../../keyword/base/KeywordWhereUniqueInput";
import { OccurrenceFindManyArgs } from "../../occurrence/base/OccurrenceFindManyArgs";
import { Occurrence } from "../../occurrence/base/Occurrence";
import { OccurrenceWhereUniqueInput } from "../../occurrence/base/OccurrenceWhereUniqueInput";

export class DetectionControllerBase {
  constructor(protected readonly service: DetectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Detection })
  async createDetection(
    @common.Body() data: DetectionCreateInput
  ): Promise<Detection> {
    return await this.service.createDetection({
      data: data,
      select: {
        createdAt: true,
        id: true,
        state: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Detection] })
  @ApiNestedQuery(DetectionFindManyArgs)
  async detections(@common.Req() request: Request): Promise<Detection[]> {
    const args = plainToClass(DetectionFindManyArgs, request.query);
    return this.service.detections({
      ...args,
      select: {
        createdAt: true,
        id: true,
        state: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Detection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async detection(
    @common.Param() params: DetectionWhereUniqueInput
  ): Promise<Detection | null> {
    const result = await this.service.detection({
      where: params,
      select: {
        createdAt: true,
        id: true,
        state: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Detection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDetection(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() data: DetectionUpdateInput
  ): Promise<Detection | null> {
    try {
      return await this.service.updateDetection({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          state: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Detection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDetection(
    @common.Param() params: DetectionWhereUniqueInput
  ): Promise<Detection | null> {
    try {
      return await this.service.deleteDetection({
        where: params,
        select: {
          createdAt: true,
          id: true,
          state: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/keywords")
  @ApiNestedQuery(KeywordFindManyArgs)
  async findKeywords(
    @common.Req() request: Request,
    @common.Param() params: DetectionWhereUniqueInput
  ): Promise<Keyword[]> {
    const query = plainToClass(KeywordFindManyArgs, request.query);
    const results = await this.service.findKeywords(params.id, {
      ...query,
      select: {
        createdAt: true,

        detection: {
          select: {
            id: true,
          },
        },

        id: true,
        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/keywords")
  async connectKeywords(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: KeywordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keywords: {
        connect: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/keywords")
  async updateKeywords(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: KeywordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keywords: {
        set: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/keywords")
  async disconnectKeywords(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: KeywordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keywords: {
        disconnect: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/occurrences")
  @ApiNestedQuery(OccurrenceFindManyArgs)
  async findOccurrences(
    @common.Req() request: Request,
    @common.Param() params: DetectionWhereUniqueInput
  ): Promise<Occurrence[]> {
    const query = plainToClass(OccurrenceFindManyArgs, request.query);
    const results = await this.service.findOccurrences(params.id, {
      ...query,
      select: {
        count: true,
        createdAt: true,

        detection: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/occurrences")
  async connectOccurrences(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: OccurrenceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      occurrences: {
        connect: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/occurrences")
  async updateOccurrences(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: OccurrenceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      occurrences: {
        set: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/occurrences")
  async disconnectOccurrences(
    @common.Param() params: DetectionWhereUniqueInput,
    @common.Body() body: OccurrenceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      occurrences: {
        disconnect: body,
      },
    };
    await this.service.updateDetection({
      where: params,
      data,
      select: { id: true },
    });
  }
}
